---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: add the python sni support to legacy python installations
  include: python_sni.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_python_version is version_compare('2.6.0', '>=')
    - ansible_python_version is version_compare('2.7.9', '<')

- name: install ansible support packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ minio_ansible_support_packages }}"

- include: server.yml
  when: minio_install_server

- include: client.yml
  when: minio_install_client
