---

scenario:
  name: alternative

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: minio-centos-8
    image: paulfantom/centos-molecule:8
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: minio-ubuntu-20.04
    image: paulfantom/ubuntu-molecule:20.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/destroy.yml

lint: |
  set -e
  yamllint .

verifier:
  name: testinfra
  options:
    vvv: True
  additional_files_or_dirs:
    - ../resources/tests/
