---
name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/pavelpikta/docker-ansible-ci:2.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lints
        run: |
          yamllint . -c .yamllint
          ansible-lint -c .ansible-lint
  molecule:
    needs: lint
    runs-on: ubuntu-latest
    container: ghcr.io/pavelpikta/docker-ansible-ci:2.9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Molecule
        run: |
          pip3 install ansible ansible-lint
          pip3 install molecule[lint,docker]==3.2.3

          molecule test -s default
